name: CI/CD - Angular + Docker (GHCR)

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
    types: [closed]

permissions:
  contents: read
  packages: write

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Node.js setup (pour lint & tests)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Lint
      - name: Run Lint
        run: npm run lint

      # 5️⃣ Tests unitaires
      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # 6️⃣ Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 7️⃣ Login GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 8️⃣ Build & Push Docker image
      - name: Build and push Docker image
        run: |
          # Convert GitHub owner to lowercase
          OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')

          # Build Docker image with tags
          docker build \
          -t ghcr.io/$OWNER/tn-airbnb-web:latest \
          -t ghcr.io/$OWNER/tn-airbnb-web:${GITHUB_SHA} \
          .

          # Push Docker image to GHCR
          docker push ghcr.io/$OWNER/tn-airbnb-web:latest
          docker push ghcr.io/$OWNER/tn-airbnb-web:${GITHUB_SHA}   
    
  continuous-deploy:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Deploy Docker Compose locally
        run: |
              cd C:/Users/wael-pc/tn-airbnb-web
              docker-compose pull
              docker-compose down
              docker-compose up -d